// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqjzdwFQPOpRS6TdNBbptntxbbVHYmGeI',
    appId: '1:727144715725:web:515f6e06e1dc43e03fa084',
    messagingSenderId: '727144715725',
    projectId: 'ff-crudpage-exampl',
    authDomain: 'ff-crudpage-exampl.firebaseapp.com',
    storageBucket: 'ff-crudpage-exampl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhwAh2-04v5OxarFelJJV4CsVqOzclInI',
    appId: '1:727144715725:android:d4e9690368e6fdcc3fa084',
    messagingSenderId: '727144715725',
    projectId: 'ff-crudpage-exampl',
    storageBucket: 'ff-crudpage-exampl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhWJSW9P0JeGEO7i7PAr1Kflc70COXg3s',
    appId: '1:727144715725:ios:b3d2128ab1b882a13fa084',
    messagingSenderId: '727144715725',
    projectId: 'ff-crudpage-exampl',
    storageBucket: 'ff-crudpage-exampl.appspot.com',
    iosClientId: '727144715725-frpviet0pevs1pingnbalnqrv72qrp13.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhWJSW9P0JeGEO7i7PAr1Kflc70COXg3s',
    appId: '1:727144715725:ios:b3d2128ab1b882a13fa084',
    messagingSenderId: '727144715725',
    projectId: 'ff-crudpage-exampl',
    storageBucket: 'ff-crudpage-exampl.appspot.com',
    iosClientId: '727144715725-frpviet0pevs1pingnbalnqrv72qrp13.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
